version: '3.3'

services:
    web:
        build: ./web
        ports: 
            - "1616:1616"
        volumes:
            - ./web/:/home/web/
            - ./files:/home/files/
        env_file:
            - .env